apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        # Replace the Account ID and Region with your actual ECR URL
        image: 161007500783.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
        # Note: Change '80' to 8080 or 3000 if your backend uses a different port